export const FILTER_WORKSPACES = 'FILTER_WORKSPACES';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const LOAD_WORKSPACES_DATA = 'LOAD_WORKSPACES_DATA';
export const ENABLE_DARK_MODE = 'ENABLE_DARK_MODE';
export const DISABLE_DARK_MODE = 'DISABLE_DARK_MODE';
